# Week 12-14

## Quiz 8

1. In `FuncAnimation`, what does the `interval` argument do?  Example below.

        anim = FuncAnimation(fig=fig,func=animate,interval=100,repeat=False)

2. Provide an example of how to open a text file and extract the text data (You can use `example.txt` in your example).

3. Use a shift 5 cipher to encrypt the following message.

        message = 'One ring to rule them all.'

In [ ]:
with open('example.txt') as f:
    text = f.read()

In [ ]:
f = open('example.txt')
text = f.read()
f.close()

In [1]:
def shift_cipher1(mes,alph,key):
    encrypted_message = ''
    for char in mes:
        encrypted_message += alph[(alph.index(char)+key)%len(alph)]
    return encrypted_message

In [2]:
message = 'One ring to rule them all.'

In [3]:
alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz.,!? '

In [4]:
shift_cipher1(message,alphabet,5)

'TsjEwnslEytEwzqjEymjrEfqqA'

## Notes

In [5]:
import numpy as np

In [6]:
A = np.ones((5,8))
print(A)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [8]:
B = np.reshape(A,(2,20))
print(B)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [9]:
A1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(A1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
B1 = np.reshape(A1,(2,6))
print(B1)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


### Project 8, Solving Sudoku

Write a function that opens the file `sudokus.txt` and loads the initial sudoku configurations as numpy arrays.

In [21]:
import numpy as np

In [40]:
def print_sudoku(arr): # arr is a 9x9 numpy array
    for i in range(9):
        for j in range(9):
            x = arr[i, j] if arr[i, j] != 0 else "."
            print(f" {x} ", end="")
            if j in [2, 5]:
                print("\u2551", end="")
        print("")
        if i in [2, 5]:
            print("\u2550"*9 + "\u256C" + "\u2550"*9 + "\u256C" + "\u2550"*9)

In [19]:
load_sudokus('sudokus.txt')[0]

array([[0, 4, 0, 0, 0, 0, 1, 7, 9],
       [0, 0, 2, 0, 0, 8, 0, 5, 4],
       [0, 0, 6, 0, 0, 5, 0, 0, 8],
       [0, 8, 0, 0, 7, 0, 9, 1, 0],
       [0, 5, 0, 0, 9, 0, 0, 3, 0],
       [0, 1, 9, 0, 6, 0, 0, 4, 0],
       [3, 0, 0, 4, 0, 0, 7, 0, 0],
       [5, 7, 0, 1, 0, 0, 2, 0, 0],
       [9, 2, 8, 0, 0, 0, 0, 6, 0]])

In [ ]:
sudokus = load_sudokus('sudokus.txt')

In [21]:
print_sudoku(sudokus[0])

 .  4  . ║ .  .  . ║ 1  7  9 
 .  .  2 ║ .  .  8 ║ .  5  4 
 .  .  6 ║ .  .  5 ║ .  .  8 
═════════╬═════════╬═════════
 .  8  . ║ .  7  . ║ 9  1  . 
 .  5  . ║ .  9  . ║ .  3  . 
 .  1  9 ║ .  6  . ║ .  4  . 
═════════╬═════════╬═════════
 3  .  . ║ 4  .  . ║ 7  .  . 
 5  7  . ║ 1  .  . ║ 2  .  . 
 9  2  8 ║ .  .  . ║ .  6  . 


In [10]:
row = [2,8,5,4]
column = [7,9,6]
square = [8,5]

In [11]:
row_set = set(row)
col_set = set(column)
sq_set = set(square)

In [12]:
print(row_set)

{8, 2, 4, 5}


In [13]:
8 in row_set

True

In [14]:
9 in row_set

False

In [15]:
set1 = {1,2,3,4,5,6,7,8,9}
set2 = {2,4,6,8}

In [16]:
set3 = set1 - set2
print(set3)

{1, 3, 5, 7, 9}


In [18]:
{1,2,4,5,7,8,10}.intersection(set3)

{1, 5, 7}

In [50]:
set3.union(set2)

{1, 2, 3, 4, 5, 6, 7, 8, 9}

In [51]:
len(set2)

4