# Week 12 Notes

In [1]:
s = open('sudokus.txt')
lines = []
for line in s:
    lines.append(line.strip('\n').split())
s.close()
lines

[[],
 ['0', '4', '0', '0', '0', '0', '1', '7', '9'],
 ['0', '0', '2', '0', '0', '8', '0', '5', '4'],
 ['0', '0', '6', '0', '0', '5', '0', '0', '8'],
 ['0', '8', '0', '0', '7', '0', '9', '1', '0'],
 ['0', '5', '0', '0', '9', '0', '0', '3', '0'],
 ['0', '1', '9', '0', '6', '0', '0', '4', '0'],
 ['3', '0', '0', '4', '0', '0', '7', '0', '0'],
 ['5', '7', '0', '1', '0', '0', '2', '0', '0'],
 ['9', '2', '8', '0', '0', '0', '0', '6', '0'],
 [],
 ['8', '0', '2', '0', '5', '0', '7', '0', '1'],
 ['0', '0', '7', '0', '8', '2', '4', '6', '0'],
 ['0', '1', '0', '9', '0', '0', '0', '0', '0'],
 ['6', '0', '0', '0', '0', '1', '8', '3', '2'],
 ['5', '0', '0', '0', '0', '0', '0', '0', '9'],
 ['1', '8', '4', '3', '0', '0', '0', '0', '6'],
 ['0', '0', '0', '0', '0', '4', '0', '2', '0'],
 ['0', '9', '5', '6', '1', '0', '3', '0', '0'],
 ['3', '0', '8', '0', '9', '0', '6', '0', '7'],
 [],
 ['0', '0', '0', '0', '0', '0', '0', '0', '7'],
 ['7', '2', '0', '3', '0', '9', '0', '0', '1'],
 ['0', '0', '8', '7', '0'

In [2]:
import numpy as np

In [3]:
first_sudoku = lines[1:10]
first_sudoku

[['0', '4', '0', '0', '0', '0', '1', '7', '9'],
 ['0', '0', '2', '0', '0', '8', '0', '5', '4'],
 ['0', '0', '6', '0', '0', '5', '0', '0', '8'],
 ['0', '8', '0', '0', '7', '0', '9', '1', '0'],
 ['0', '5', '0', '0', '9', '0', '0', '3', '0'],
 ['0', '1', '9', '0', '6', '0', '0', '4', '0'],
 ['3', '0', '0', '4', '0', '0', '7', '0', '0'],
 ['5', '7', '0', '1', '0', '0', '2', '0', '0'],
 ['9', '2', '8', '0', '0', '0', '0', '6', '0']]

In [4]:
first_array = np.array(first_sudoku,dtype=int)

In [5]:
first_array

array([[0, 4, 0, 0, 0, 0, 1, 7, 9],
       [0, 0, 2, 0, 0, 8, 0, 5, 4],
       [0, 0, 6, 0, 0, 5, 0, 0, 8],
       [0, 8, 0, 0, 7, 0, 9, 1, 0],
       [0, 5, 0, 0, 9, 0, 0, 3, 0],
       [0, 1, 9, 0, 6, 0, 0, 4, 0],
       [3, 0, 0, 4, 0, 0, 7, 0, 0],
       [5, 7, 0, 1, 0, 0, 2, 0, 0],
       [9, 2, 8, 0, 0, 0, 0, 6, 0]])

In [6]:
sudokus = []
for i in range(6):
    sudoku = lines[10*i+1:10*i+10]
    sudoku_array = np.array(sudoku,dtype=int)
    sudokus.append(sudoku_array)
sudokus

[array([[0, 4, 0, 0, 0, 0, 1, 7, 9],
        [0, 0, 2, 0, 0, 8, 0, 5, 4],
        [0, 0, 6, 0, 0, 5, 0, 0, 8],
        [0, 8, 0, 0, 7, 0, 9, 1, 0],
        [0, 5, 0, 0, 9, 0, 0, 3, 0],
        [0, 1, 9, 0, 6, 0, 0, 4, 0],
        [3, 0, 0, 4, 0, 0, 7, 0, 0],
        [5, 7, 0, 1, 0, 0, 2, 0, 0],
        [9, 2, 8, 0, 0, 0, 0, 6, 0]]),
 array([[8, 0, 2, 0, 5, 0, 7, 0, 1],
        [0, 0, 7, 0, 8, 2, 4, 6, 0],
        [0, 1, 0, 9, 0, 0, 0, 0, 0],
        [6, 0, 0, 0, 0, 1, 8, 3, 2],
        [5, 0, 0, 0, 0, 0, 0, 0, 9],
        [1, 8, 4, 3, 0, 0, 0, 0, 6],
        [0, 0, 0, 0, 0, 4, 0, 2, 0],
        [0, 9, 5, 6, 1, 0, 3, 0, 0],
        [3, 0, 8, 0, 9, 0, 6, 0, 7]]),
 array([[0, 0, 0, 0, 0, 0, 0, 0, 7],
        [7, 2, 0, 3, 0, 9, 0, 0, 1],
        [0, 0, 8, 7, 0, 5, 0, 6, 0],
        [5, 0, 2, 8, 9, 0, 0, 0, 0],
        [0, 4, 0, 5, 0, 1, 0, 9, 0],
        [0, 0, 0, 0, 6, 3, 7, 0, 5],
        [0, 3, 0, 9, 0, 6, 1, 0, 0],
        [2, 0, 0, 1, 0, 7, 0, 5, 3],
        [9, 0, 0, 0, 0, 0, 0, 0, 0

In [7]:
def print_sudoku(arr): # arr is a 9x9 numpy array
    for i in range(9):
        for j in range(9):
            x = arr[i, j] if arr[i, j] != 0 else "."
            print(f" {x} ", end="")
            if j in [2, 5]:
                print("\u2551", end="")
        print("")
        if i in [2, 5]:
            print("\u2550"*9 + "\u256C" + "\u2550"*9 + "\u256C" + "\u2550"*9)

In [8]:
print_sudoku(sudokus[0])

 .  4  . ║ .  .  . ║ 1  7  9 
 .  .  2 ║ .  .  8 ║ .  5  4 
 .  .  6 ║ .  .  5 ║ .  .  8 
═════════╬═════════╬═════════
 .  8  . ║ .  7  . ║ 9  1  . 
 .  5  . ║ .  9  . ║ .  3  . 
 .  1  9 ║ .  6  . ║ .  4  . 
═════════╬═════════╬═════════
 3  .  . ║ 4  .  . ║ 7  .  . 
 5  7  . ║ 1  .  . ║ 2  .  . 
 9  2  8 ║ .  .  . ║ .  6  . 


### Solving Sudoku

For the blank entry (i,j) position
* Keep track of list of possible choices
  1. Start out with the numbers 1 through 9
  2. Eliminate the numbers in the same square
  3. Eliminate the numbers in the same row
  4. Eliminate the numbers in the same column