# Week 6 Notes

## Random Library

In [6]:
import random as r

In [10]:
r.random()

0.705513226934028

In [11]:
for i in range(20):
    num = r.random()
    print(num)

0.7319589730332557
0.43351443489540376
0.8000204571334277
0.5329014146425713
0.08015370917850195
0.45594588118356716
0.047887516459941715
0.9329624000750505
0.9470780060029439
0.33535077594001006
0.3094059291400342
0.7680181487450805
0.20386952877685705
0.17846076295399127
0.18859491417448548
0.34700445361481724
0.6263216391927974
0.9633157837008631
0.21083399208685016
0.9561006461166511


In [18]:
r.seed(150)
r.random()

0.823807241964088

### Using random() to model coin flip

Flip a fair coin with 50% probability of landing on heads.  Model using a function.

In [36]:
def toss_coin(p=0.5):          # p is the probability of heads between 0 and 1
    x = r.random()
    if x < p:
        toss_value = 'H'
    else:
        toss_value = 'T'
    return toss_value

In [39]:
toss_coin()

'H'

In [40]:
for i in range(20):
    toss = toss_coin()
    print(toss)

T
H
T
H
T
H
H
T
H
T
H
H
T
H
H
T
H
T
H
H


In [42]:
def coin_toss_trial(n,p=0.5):                # n is the number of coin tosses
    num_of_heads = 0
    num_of_tails = 0
    for i in range(n):
        toss = toss_coin(p)
        if toss == 'H':
            num_of_heads += 1
        else:
            num_of_tails += 1
    return [('H',num_of_heads), ('T',num_of_tails)]

In [44]:
coin_toss_trial(20000)

[('H', 10079), ('T', 9921)]

### Rolling a dice using randint()

In [52]:
r.randint(0,10)


7

In [53]:
for i in range(20):
    x = r.randint(0,10)   # right endpoint is included
    print(x)

5
2
2
9
3
7
8
10
0
4
3
8
6
10
8
10
7
7
10
5


In [59]:
def roll_dice(s=6):
    roll_value = r.randint(1,s)
    return roll_value

In [56]:
roll_dice()

6

In [60]:
for i in range(20):
    print(roll_dice(20))

15
4
2
6
2
14
7
8
11
17
4
1
4
17
11
18
15
5
9
6


### Drawing a colored stone from a bag of stones

In [61]:
def draw_stone(red_stones,blue_stones,num_of_draws):
    bag = ['R' for i in range(red_stones)] + ['B' for i in range(blue_stones)]
    num_red = 0
    num_blue = 0
    for i in range(num_of_draws):
        index = r.randint(0,len(bag)-1)
        stone = bag.pop(index)
        if stone == 'R':
            num_red += 1
        else:
            num_blue += 1
    return [('R',num_red),('B',num_blue)]

In [67]:
draw_stone(20,15,5)

[('R', 3), ('B', 2)]

### Exercise
1.  Write a function to perform n trials of the roll dice function and aggregate the results
2.  Write a function to perform n trials of the draw stone function and aggregate the results
3.  Run both function for 1000 trials.

# Numpy arrays

In [1]:
import numpy as np

In [2]:
A = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [3]:
list1 = []
for i in range(3):
    list2 = []
    for j in range(4):
        list2.append(j)
    list1.append(list2)
list1

[[0, 1, 2, 3], [0, 1, 2, 3], [0, 1, 2, 3]]

In [4]:
B = np.array(list1)
print(B)

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


In [5]:
np.shape(B)

(3, 4)

In [6]:
np.shape(B)[1]

4

In [7]:
C = np.ones([8,10])
print(C)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [9]:
C2 = np.ones([8,10],dtype = int)
print(C2)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [10]:
D = np.zeros([8,10])
print(D)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


### Stepping through an array

In [11]:
#  A is an array
m,n = np.shape(A)
for i in range(m):         # Stepping through the rows
    for j in range(n):     # Stepping through the columns in each row
        print(A[i,j])


1
2
3
4
5
6
7
8
9
10
11
12


In [12]:
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [14]:
m,n = np.shape(A)
for tup in [(i,j) for i in range(m) for j in range(n)]:
    print(A[tup])

1
2
3
4
5
6
7
8
9
10
11
12


In [15]:
A[2,3]

12

In [16]:
A[1,0]

5

In [17]:
A[1,:]

array([5, 6, 7, 8])

In [18]:
A[:,1]

array([ 2,  6, 10])

In [19]:
A[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [20]:
A[1:,1:3]

array([[ 6,  7],
       [10, 11]])

#### Broadcasting

In [21]:
array1 = np.zeros([10,10])
print(array1)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [24]:
array1[3:7,3:7] = np.ones([4,4])
print(array1)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [25]:
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [26]:
print(B)

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


In [27]:
A+B

array([[ 1,  3,  5,  7],
       [ 5,  7,  9, 11],
       [ 9, 11, 13, 15]])

In [28]:
10* A

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [29]:
array2 = np.ones([10,10])

In [30]:
array2 = array2 * 10

In [31]:
array2[:9,:9] = np.ones([9,9])*9

In [32]:
print(array2)

[[ 9.  9.  9.  9.  9.  9.  9.  9.  9. 10.]
 [ 9.  9.  9.  9.  9.  9.  9.  9.  9. 10.]
 [ 9.  9.  9.  9.  9.  9.  9.  9.  9. 10.]
 [ 9.  9.  9.  9.  9.  9.  9.  9.  9. 10.]
 [ 9.  9.  9.  9.  9.  9.  9.  9.  9. 10.]
 [ 9.  9.  9.  9.  9.  9.  9.  9.  9. 10.]
 [ 9.  9.  9.  9.  9.  9.  9.  9.  9. 10.]
 [ 9.  9.  9.  9.  9.  9.  9.  9.  9. 10.]
 [ 9.  9.  9.  9.  9.  9.  9.  9.  9. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]]


In [33]:
array2[:8,:8] = np.ones([8,8])*8
print(array2)

[[ 8.  8.  8.  8.  8.  8.  8.  8.  9. 10.]
 [ 8.  8.  8.  8.  8.  8.  8.  8.  9. 10.]
 [ 8.  8.  8.  8.  8.  8.  8.  8.  9. 10.]
 [ 8.  8.  8.  8.  8.  8.  8.  8.  9. 10.]
 [ 8.  8.  8.  8.  8.  8.  8.  8.  9. 10.]
 [ 8.  8.  8.  8.  8.  8.  8.  8.  9. 10.]
 [ 8.  8.  8.  8.  8.  8.  8.  8.  9. 10.]
 [ 8.  8.  8.  8.  8.  8.  8.  8.  9. 10.]
 [ 9.  9.  9.  9.  9.  9.  9.  9.  9. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]]


In [34]:
array2 = np.ones([10,10])*10
for i in range(9):
    array2[:(9-i),:(9-i)] = np.ones([9-i,9-i])*(9-i)
print(array2)

[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 2.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 3.  3.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 4.  4.  4.  4.  5.  6.  7.  8.  9. 10.]
 [ 5.  5.  5.  5.  5.  6.  7.  8.  9. 10.]
 [ 6.  6.  6.  6.  6.  6.  7.  8.  9. 10.]
 [ 7.  7.  7.  7.  7.  7.  7.  8.  9. 10.]
 [ 8.  8.  8.  8.  8.  8.  8.  8.  9. 10.]
 [ 9.  9.  9.  9.  9.  9.  9.  9.  9. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]]
