## Week 15

In [1]:
def print_sudoku(arr): # arr is a 9x9 numpy array
    for i in range(9):
        for j in range(9):
            x = arr[i, j] if arr[i, j] != 0 else "."
            print(f" {x} ", end="")
            if j in [2, 5]:
                print("\u2551", end="")
        print("")
        if i in [2, 5]:
            print("\u2550"*9 + "\u256C" + "\u2550"*9 + "\u256C" + "\u2550"*9)

In [2]:
import numpy as np

In [14]:
pippo=np.random.randint(10,size=(9,9))
print(pippo)

[[6 5 9 4 6 4 7 9 7]
 [0 8 6 2 0 2 1 6 5]
 [9 4 6 0 2 6 2 5 2]
 [3 9 5 8 7 9 0 5 4]
 [6 1 3 1 4 7 7 6 9]
 [1 1 8 3 3 8 2 3 9]
 [4 9 6 7 7 2 5 7 1]
 [5 3 1 3 7 3 4 4 5]
 [2 8 1 7 7 3 7 8 3]]


In [13]:
print_sudoku(pippo)

 1  3  1 ║ 3  3  4 ║ 4  2  2 
 8  8  8 ║ 5  1  7 ║ 2  5  2 
 .  6  4 ║ 5  8  1 ║ 6  6  5 
═════════╬═════════╬═════════
 8  3  4 ║ 4  8  . ║ 2  6  2 
 3  2  3 ║ 4  2  7 ║ 2  .  4 
 6  8  1 ║ 4  4  . ║ 7  3  1 
═════════╬═════════╬═════════
 7  7  . ║ 4  8  5 ║ 3  5  5 
 6  2  1 ║ 8  7  5 ║ 8  8  3 
 8  .  3 ║ 7  7  8 ║ 3  5  6 


**Hint**: create 3 helper functions that for position [i,j] they will check row i, col j, and the correct 3x3 subgrid.

### Recursion (necessary to solve harder sudokus)

A recursive function, is a function that call itself

**example** factorial: $n!=n\cdot(n-1)\cdot(n-2)\cdots 2 \cdot 1$

factorial: $n!= n \cdot (n-1)!$

In [17]:
def fact(n):
    if n<2:
        return 1
    else:
        return n*fact(n-1)

In [18]:
fact(4)

24

**Ex.** write a recursive function for Santa's gift delivery

* Given a list of houses: `house_list`
* if the list has 1 house on it -> deliver gifts
* otherwise -> split list in half and find 2 more elves

In [2]:
mylist=["Simone's house","Rosella's house","Amy's house","Lucia's house","Pippo's house"]

output:

Delivery to Simone's house

Delivery to Rosella's house

Delivery to Amy's house

....

In [4]:
def delivery_recursive(myl):
    
    if len(myl)==0:
        print('No delivery necessary')
    elif len(myl)==1:
        print(f'Santa is delivering present to {myl[0]}')
    else:
        middle=len(myl)//2
        myl1=myl[:middle]
        myl2=myl[middle:]
        delivery_recursive(myl1)
        delivery_recursive(myl2)

In [5]:
delivery_recursive(mylist)

Santa is delivering present to Simone's house
Santa is delivering present to Rosella's house
Santa is delivering present to Amy's house
Santa is delivering present to Lucia's house
Santa is delivering present to Pippo's house


In [82]:
sudoku_string='''0 0 1 7 2 5 0 0 0
0 8 0 0 1 0 0 0 6
2 5 0 0 0 0 1 3 0
0 7 0 0 0 0 5 0 0
0 0 0 1 0 6 0 0 0
0 0 9 0 0 0 0 8 0
0 4 5 0 0 0 0 2 9
7 0 0 0 9 0 0 6 0
0 0 0 6 4 8 3 0 0'''

**Function** : `sudoku_solver(sudoku_matrix)` -> **Output**: solved sudoku

1. Put the string into 9x9 a numpy array
2. define `check_rows`
3. define `check_col`
4. define `check_sq`
5. If sudoku entry `[i,j]` =0 -> check row,col,sq to find the number that goes in position [i,j]
6. If only one number goes in pos `[i,j]`, plug it in, otherwise don't plug in in position `[i,j]`
7. Repeat 5-6 until all the entries are not zero

In [5]:
import numpy as np

In [12]:
sudoku_array=np.empty(81)
# fill the array

In [11]:
sudoku_matrix=sudoku_array.reshape(9,9)

In [79]:
def check_row(i,sudoku): # i is the row index
    num={1,2,3,4,5,6,7,8,9}-set(sudoku[i,:])
    return num # a set of the numbers that can fit into the box
    